### ISSUE TITLE
Adding preprocessing functions

### ISSUE THREAD

**Issue by joschif** [theislab/CellFlow#79]
### Description of feature

Might be nice to add some more preprocessing utility functions to prepare the adata for training. E.g.
* computing PCA 
* molecule smiles/fingerprints
* onehot encoding
* maybe even ESM-2/protein embeddings?
* etc... 

In terms of interface, we could have a preprocessing module analogous to scanpy (e.g. `cfp.pp.encode_onehot()`) with functions that modify the adata in place and add things to `obsm`/`uns`, etc. 

I stared drafting something in #78. Would be great to get your input what you think is best for this.

**Comment by shuhuiwang1** [comment]
It is great to have the preprocessing to annotate smiles! However, I found that when I used CellFlow code, for example on combsciplex data or sciplex3 data, non of drugs in these two datasets could get smiles annotation. Did you use any specific version of pertpy or pubchempy packages? Thank you in advance.
